### PR TITLE
[feat] Clean Page Framework

### LINKED ISSUE #13: [feat] Implement Step State Logic in Data Cleaning Part
## Description
Develop a step state management system to handle the sub-steps within the data cleaning process. This will ensure users can move through the 3 steps which is handling missing data, removing duplicate entries, and validating column entries efficiently.

## Steps
1. **Handling Missing Data**: Options for interpolation, imputation, or removal of missing data.
2. **Removing Duplicate Entries**: Detect and remove duplicate rows based on a chosen set of columns.
3. **Validating Column Entries**: Ensure that specific columns meet defined criteria (e.g., data type checks, value ranges, etc.).

## Tasks
- [x] #16 

## Additional Info
- Users can navigate forward and backward within the data cleaning sub-steps.
- Current sub-step state is synchronized with a visual indicator, such as a stepper, to guide users through the data cleaning process.
- Each sub-step displays corresponding UI components for user input and interaction.

### PR DESCRIPTION
**Pull request by Gidsss**
### CleanPage
- Refactored stepper navigation to allow dynamic transitions between steps.
- Ensured the "Next" button is disabled until the current step is completed.
- Implemented logic to display the "Finish" button for the last step.
- Adjusted styling for step labels for better user interaction.

### CleanRibbon
- Added conditional logic to display the "Proceed" button only after all steps are completed.
- Integrated cleaning step triggers to handle missing data, duplicates, and column validation.
- Improved tooltips for better action context.

### CsvContext
- Introduced advanced data cleaning methods with improved performance using lodash.
- Added missing data handling with preview alerts for cleaned data.
- Implemented duplicate detection and removal with unique preview alerts (should be duplicated haha).
- Enhanced column validation with conversion for numerical string values.

### StepContext
- Refined step completion tracking to address navigation issues.
- Enhanced logic to allow step label clicking for completed steps only.
- Fixed issues with backward navigation alerts.
- Introduced a helper method for managing current step completion.

Sample Demo:

https://github.com/user-attachments/assets/4f1906f9-efaa-4100-b0a3-35a056dc74e5

### CODE REVIEW

**Comment by Gidsss** [comment]
image

Will adjust the code to follow the UI/UX design, thanks!

**Comment by Gidsss** [comment]
https://github.com/user-attachments/assets/c1113268-1df9-4d39-8a09-b97d3f195de9

**Review by seegyulater — APPROVED** [review]
lgtm!

**Review by HolyShaq — APPROVED** [review]
lgtm! Only suggestion ko nalang is kapag clinick ung mga buttons na tapos na or kapag malinis naman na ung dataset, show a popup nalang na "no missing data found" ganon. 

Right now kasi, pag pinindot ulit ung mga buttons na tapos na, nagdidisplay ulit ung natanggal na data and nawawala ung proceed button.

**Comment by Gidsss** [comment]
> lgtm! Only suggestion ko nalang is kapag clinick ung mga buttons na tapos na or kapag malinis naman na ung dataset, show a popup nalang na "no missing data found" ganon.
> 
> Right now kasi, pag pinindot ulit ung mga buttons na tapos na, nagdidisplay ulit ung natanggal na data and nawawala ung proceed button.

Yeah mas maganda nga yan ggg, much better if handle na yan sa paggawa mismo nung methods for data cleaning

**Pull request merged**
