### PR TITLE
Suggestion for codebase structure

### PR DESCRIPTION
**Pull request by HolyShaq**
Suggest ko lang tong project structure na ganito:

src/
├─ app/
├─ components/
├─ lib/

`app` - dito lalagay ung mga page.tsx
`components` - dito lalagay ung mga components na iiinstall from mui, as well as custom components
`lib`- dito lalagay mga utility functions like api request handling

Ganto kasi ginawa namin before nung nagwork kami on next js, pede ko send repo non if gusto nio makita

### CODE REVIEW

**Comment by Gidsss** [comment]
lgtm!

**Comment by seegyulater** [comment]
same here lgtm! wohooo!

**Comment by dssrts** [comment]
LeGTiMate

**Comment by HolyShaq** [comment]
Approve!

**Review by seegyulater — COMMENTED** [review]
iloveu

**Pull request merged**
