### PR TITLE
[feat] Visualization Page Framework

### PR DESCRIPTION
**Pull request by HolyShaq**
### ChartContext
- context for interacting with the Visualization page
- reference `figure` to get list of figures
- use `addFigure` and `removeFigure` to modify figure list

### StepModal
- modal component that allows you to choose a column from the uploaded data
- use `setChoice` to get chosen value
- use `onConfirm` and `onClose` to add additional functionality to the confirm and close buttons
- set `optional` if choice can be skipped (not yet implemented)
- set `mustBeNumber` to convert columns with string values to either count, average, min, max, etc. the string values (not yet implemented)

### Framework
- for every chart type, create a `{ChartType}Modals.tsx` and define the needed `StepModal` components there. See `BarChartModals.tsx` as an example

https://github.com/user-attachments/assets/c4c8a92c-a87e-4979-8cbb-46dec99940f7

### CODE REVIEW

**Comment by Gidsss** [comment]
Off-topic pero, pano mo pinagana yung referencing, like ang problema ko kasi yung sa cleanribbon actions ko di gumagana like I think related siya sa `csvData` unless explicitly naidedeclare ko yung <CleanRibbon handleAction={handleAction}/> sa CleanPage hindi gumagana yung handleAction ko? Btw ginawa ko rin na asa `StepContext` yung logic for it like for cleaning data for step 1 to step 3? Ano suggestion mo? @HolyShaq

**Comment by HolyShaq** [comment]
Regarding dun sa logic ng cleaning steps, I think mas maganda if separate context file siya. Para lang mas maging organized. Madadagdagan lang naman ng isa pang provider sa page.tsx no problemo

Dun sa problem mo abt referencing, sa gc nlng pag usapan HAHAHAHAHA para live

**Review by Gidsss — APPROVED** [review]
lgtm, merge na tomorrow para updated na rin yung branch na ginagawan ko for data cleaning! (No conflicts naman sa ginagawa ko since magkaibang files)

**Review by seegyulater — APPROVED** [review]
looks good to me!! thanks na plot na ung sa visualization

**Pull request merged**
